apiVersion: v1
kind: Service
metadata:
  name: radis
  labels:
    name: radis-service
    app: demo-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: radis-pod
    app: demo-voting-app
